name = "comfig-api"
main = "src/index.ts"
compatibility_date = "2024-05-13"

[[durable_objects.bindings]]
name = "HUD_COUNT"
class_name = "HudDownloadCounter"

[[migrations]]
tag = "v1"
new_classes = ["HudDownloadCounter"]
