name = "comfig-api"
main = "src/index.ts"
compatibility_date = "2024-05-13"

[[durable_objects.bindings]]
name = "HUD_COUNT"
class_name = "HudDownloadCounter"

[[migrations]]
tag = "v1"
new_classes = ["HudDownloadCounter"]

[[kv_namespaces]]
binding = "QUICKPLAY"
id = "2fa7e82570f845b78e0357500b055ad4"
